version: '2.1'

services:
  webconsole-images:
    image: joyent/webconsole-images:1.0.0
    restart: always
    mem_limit: 1g
    network_mode: bridge
    labels:
      - triton.cns.services=webconsole-images
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SSO_URL=https://login.samsungcloud.io/login
    ports:
      - 80:80
