version: '2.1'

services:
  consul:
    image: autopilotpattern/consul:1.0.0r43
    command: >
      /usr/local/bin/containerpilot
    env_file:
      - .consul.env
    restart: always
    mem_limit: 512m
    network_mode: bridge
    labels:
      - triton.cns.services=webconsole-images-consul
    expose:
      - 9090
      - 8500

  webconsole-images:
    image: joyent/webconsole-images:1.0.0
    restart: always
    mem_limit: 1g
    network_mode: bridge
    labels:
      - triton.cns.services=webconsole-images
    env_file:
      - .env
      - .consul.env
    environment:
      - CONSUL=consul
      - NODE_ENV=production
      - SSO_URL=https://login.samsungcloud.io/login
    links:
      - consul:consul
    ports:
      - 80:80
