webconsole-images:
  build: ./
  restart: always
  mem_limit: 1g
  env_file:
    - .env
  environment:
    - COOKIE_DOMAIN=localhost
    - COOKIE_SECURE=0
    - BASE_URL=http://localhost
    - NODE_ENV=development
    - PORT=8082
    - SSO_URL=https://sso.joyent.com/login
  ports:
    - 8082:8082
